version: '3.7'
services:
  aws: 
    image: organs/awscli
    environment: 
      AWS_ACCESS_KEY_ID: -----------
      AWS_SECRET_ACCESS_KEY: --------------
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    volumes:
      - "$PWD:/app"
    working_dir: /app
  terraform:
    build: 
      context: .
      dockerfile: terraform.Dockerfile
    environment: 
      AWS_ACCESS_KEY_ID: -----------
      AWS_SECRET_ACCESS_KEY: --------------
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
    volumes:
      - "$PWD:/app"
    working_dir: /app
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5901:5900
  website:
   build:
    context: .
   ports:
    - 80:80
  integration-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/integration/*_spec.rb
  unit-tests:
    build:
      dockerfile: rspec.dockerfile
      context: .
    environment:
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    volumes:
      - $PWD:/app
    entrypoint: rspec
    command:
      - --pattern
      - /app/spec/unit/*_spec.rb
# with the course file yml and page_spec.rb, the test runs successfully
